# Generated by Django 2.0 on 2018-08-19 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='birthday',
            field=models.DateTimeField(blank=True, null=True, verbose_name='生日'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='nick_name',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='昵称'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='qq_number',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='QQ号码'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='real_name',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='真实姓名'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='remarks',
            field=models.TextField(blank=True, null=True, verbose_name='备注信息'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='wechat',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='微信帐号'),
        ),
    ]
