# Generated by Django 2.0 on 2018-08-19 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20180819_1538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='user_id',
            field=models.BigIntegerField(default=100001, editable=False, verbose_name='用户iD'),
        ),
    ]
