# Generated by Django 2.0 on 2018-08-19 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20180819_2106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='last_ip',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='上次登录IP'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user_id',
            field=models.BigIntegerField(default=100001, verbose_name='用户iD'),
        ),
    ]
