# Generated by Django 2.0 on 2018-09-01 11:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20180819_2121'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=32, unique=True, verbose_name='商品类型状态')),
            ],
        ),
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=32, unique=True, verbose_name='商品编号')),
                ('inventory_quantity', models.IntegerField(default=0, verbose_name='库存量')),
                ('last_purchasing_price', models.FloatField(blank=True, default=0.0, verbose_name='最后进货价')),
                ('min_num', models.IntegerField(blank=True, default=0, verbose_name='库存下限')),
                ('model', models.CharField(blank=True, default=0, max_length=64, verbose_name='规格型号')),
                ('name', models.CharField(default='', max_length=64, verbose_name='商品名称')),
                ('producer', models.CharField(blank=True, default=0, max_length=128, verbose_name='生产商')),
                ('purchasing_price', models.FloatField(default=0, verbose_name='进货单价')),
                ('selling_price', models.FloatField(default=0, verbose_name='销售单价')),
            ],
        ),
        migrations.CreateModel(
            name='GoodsCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.FilePathField(default='', verbose_name='图片地址')),
                ('name', models.CharField(default='', max_length=32, unique=True, verbose_name='类型名称')),
                ('level', models.IntegerField(default=1, verbose_name='类型级别')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.GoodsCategory', verbose_name='上级分类')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.CategoryState', verbose_name='节点状态')),
            ],
        ),
        migrations.CreateModel(
            name='GoodsState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=32, unique=True, verbose_name='商品状态')),
            ],
        ),
        migrations.CreateModel(
            name='GoodsUnit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=32, unique=True, verbose_name='商品单位')),
            ],
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=32, verbose_name='仓库编码')),
                ('name', models.CharField(max_length=32, verbose_name='仓库名称')),
                ('inventory_category', models.CharField(default='普通仓', max_length=32, verbose_name='仓库类型')),
                ('address', models.CharField(blank=True, max_length=64, null=True, verbose_name='仓库地址')),
                ('phone_number', models.BigIntegerField(blank=True, null=True, verbose_name='联系电话')),
            ],
        ),
        migrations.CreateModel(
            name='Stockin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.BigIntegerField(verbose_name='入库单ID')),
                ('comment', models.CharField(blank=True, max_length=256, null=True, verbose_name='描述')),
                ('order_sn', models.CharField(max_length=64, verbose_name='订单号')),
                ('add_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='添加时间')),
                ('out_time', models.DateTimeField(blank=True, null=True, verbose_name='出库时间')),
                ('stockin_type', models.CharField(default='入库', max_length=32, verbose_name='入库类型')),
            ],
        ),
        migrations.CreateModel(
            name='StockinState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=32, unique=True, verbose_name='入库状态')),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='供应商名')),
                ('contact', models.CharField(max_length=32, verbose_name='联系人')),
                ('contact_number', models.BigIntegerField(verbose_name='联系电话')),
                ('address', models.CharField(blank=True, max_length=64, null=True, verbose_name='地址')),
                ('remarks', models.TextField(blank=True, null=True, verbose_name='备注')),
            ],
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='last_ip',
            field=models.GenericIPAddressField(default='127.0.0.1', verbose_name='上次登录IP'),
        ),
        migrations.AddField(
            model_name='stockin',
            name='add_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='添加人'),
        ),
        migrations.AddField(
            model_name='stockin',
            name='inventory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Inventory', verbose_name='仓库'),
        ),
        migrations.AddField(
            model_name='stockin',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.StockinState', verbose_name='入库状态'),
        ),
        migrations.AddField(
            model_name='stockin',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Supplier', verbose_name='供应商'),
        ),
        migrations.AddField(
            model_name='goods',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.GoodsCategory', verbose_name='商品类型'),
        ),
        migrations.AddField(
            model_name='goods',
            name='default_inventory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Inventory', verbose_name='默认仓库'),
        ),
        migrations.AddField(
            model_name='goods',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.GoodsState', verbose_name='商品状态'),
        ),
        migrations.AddField(
            model_name='goods',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.GoodsUnit', verbose_name='基本单位'),
        ),
    ]
