# Generated by Django 2.0 on 2018-09-01 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20180901_1102'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categorystate',
            options={'verbose_name': '商品类型状态', 'verbose_name_plural': '商品类型状态'},
        ),
        migrations.AlterModelOptions(
            name='goods',
            options={'verbose_name': '商品信息', 'verbose_name_plural': '商品信息'},
        ),
        migrations.AlterModelOptions(
            name='goodscategory',
            options={'verbose_name': '商品类型', 'verbose_name_plural': '商品类型'},
        ),
        migrations.AlterModelOptions(
            name='goodsstate',
            options={'verbose_name': '商品状态', 'verbose_name_plural': '商品状态'},
        ),
        migrations.AlterModelOptions(
            name='goodsunit',
            options={'verbose_name': '商品单位', 'verbose_name_plural': '商品单位'},
        ),
        migrations.AlterModelOptions(
            name='inventory',
            options={'verbose_name': '仓库信息', 'verbose_name_plural': '仓库信息'},
        ),
        migrations.AlterModelOptions(
            name='stockin',
            options={'verbose_name': '入库信息', 'verbose_name_plural': '入库信息'},
        ),
        migrations.AlterModelOptions(
            name='stockinstate',
            options={'verbose_name': '入库状态', 'verbose_name_plural': '入库状态'},
        ),
        migrations.AlterModelOptions(
            name='supplier',
            options={'verbose_name': '供应商信息', 'verbose_name_plural': '供应商信息'},
        ),
        migrations.AlterField(
            model_name='goodscategory',
            name='icon',
            field=models.ImageField(height_field='url_height', upload_to='media', verbose_name='图片地址', width_field='url_width'),
        ),
    ]
